### ISSUE TITLE
Bug: Release without description causes error in Prismic Ruby client

### ISSUE THREAD

**Issue by faresd** [prismicio-community/ruby-kit#116]
If you create a Release without a description, which is possible by Publishing a document and choosing "Publish at a specific date and time", the ref returned by Prismic's API will have a null label and the Prismic client will fail to parse the entire response.

https://github.com/prismicio-community/ruby-kit/blob/1.7.0/lib/prismic/api.rb#L222

Found this in version 1.7.0, but still appears to be an issue on master. This line will fail with a "NoMethodError: undefined method `downcase' for nil:NilClass" ruby-kit/api.rb at 1.7.0 · prismicio-community/ruby-kit · GitHub 1

### Versions

- ruby-kit: 
- gem version: 

### Reproduction

<details open>
<summary>Additional Details</summary>

https://community.prismic.io/t/release-without-description-causes-error-in-prismic-ruby-client/7514

<br>

</details>

**Comment by faresd** [comment]
I don't know Ruby, but basically, I think the fix would be something like this ref['label'].nil ? nil : ref['label']. downcase

**Comment by bitboxer** [comment]
```
ref['label']?.downcase
```

would be enough
